!/bin/bash

export XDG_CACHE_HOME="/tmp/.cache"
export DISPLAY=:0

xset dpms 0 0 0
xset s off
xset -dpms

matchbox-window-manager -use_cursor no &

calibrate=/srv/http/data/shm/calibrate
if [[ -e $calibrate ]]; then
	rm $calibrate
	value=$( DISPLAY=:0 xinput_calibrator | grep Calibration | cut -d'"' -f4 )
	if [[ -n $value ]]; then
		sed -i "s/\(Calibration\"  \"\).*/\1$value\"/" /etc/X11/xorg.conf.d/99-calibration.conf
		systemctl restart localbrowser
	fi
else
	chromium --app=http://localhost --kiosk --incognito --no-sandbox --force-device-scale-factor=1
fi
